Date:Sun Apr 21 03:02:48 AM EDT 2013
Input command file generated by LEDA

#VERILOGCompiler	/package/eda/synopsys/leda-F-2011.09/amd64/bin/ve -M +no_lvs_env  -c -z -p2 -i -k03 -log /home/ecegrid/a/mg70/ece337/Project/leda-logs/compiler.log -full_log -snote +max_case+8 +max_casexz+8 -config_file /home/ecegrid/a/ece337/Class0.5u/.leda_config.tcl
#VHDLCompiler	/package/eda/synopsys/leda-F-2011.09/amd64/bin/v -M +no_lvs_env  -c -z -i -k93e -log /home/ecegrid/a/mg70/ece337/Project/leda-logs/compiler.log -full_log -snote -config_file /home/ecegrid/a/ece337/Class0.5u/.leda_config.tcl
#HOMELESS	LEDA_WORK
#Makefile-Name	LEDA_Makefile
#Makelibs-Name	LEDA_Makelibs
#Project-Name	/home/ecegrid/a/mg70/ece337/Project/leda.pro

#VHDLSuffixes
#End

#VHDLSuffixes
#End

#VERILOGSuffixes
v -
ve -
inc -
sv -
#End
#Mappings
#End
#Files LEDA_WORK
   /home/ecegrid/a/mg70/ece337/Project/source/controller.sv
#End

#VERILOGSuffixes
#End

#VHDLSuffixes
#End
#Mappings
#End
#Files LEDA_WORK
#End
#Resources
   IEEE $LEDA_PATH/amd64/resources/resource_93/IEEE 
   SNPS_EXT $LEDA_PATH/amd64/resources/resource_93/SNPS_EXT 
   STD $LEDA_PATH/amd64/resources/resource_93/STD 
   SYNOPSYS $LEDA_PATH/amd64/resources/resource_93/SYNOPSYS 
#End
